version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    network_mode: "host"
    ports:
      - 27017:27017
    restart: on-failure

  ms:
    image: ms:latest
    container_name: ms
    network_mode: "host"
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - mongodb
